server:
  port: 9010

ai:
  memory:
    max_messages: 100

logging:
  level:
    org.springframework.ai: info
    org.springframework.ai.chat.client.advisor: debug
    web: debug

spring:
  application:
    name: haikAI
    title: haikAI
    version: 0.0.1-SNAPSHOT
  reactor:
    netty:
      native: false
  banner:
    location: banner.txt
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5.4-nano
          temperature: 0.1
        embedding:
          options:
            model: text-embeddding-3-small
  #   OLLAMA CONFIGURATION
  #    ollama:
  #      chat:
  #        options:
  #          model: gemma3:1b
  data:
    mongodb:
      host: localhost
      port: 27019
      database: ai_chat
      username: ai_user
      password: ai_pass
